spring.application.name=atm
<<<<<<< HEAD
server.port=8083
=======
>>>>>>> aafa6995198c9dd17100c9487eb773139c7b9267

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/atm-db
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
